### ISSUE TITLE
CMSIS-Zone Utility for Eclipse 0.9.2 only shows CMSIS Pack plugin

### ISSUE THREAD

**Issue by ThorstenSt** [ARM-software/CMSIS-Zone#2]
In contrast to 0.9.0 the zipped plugin v0.9.2 only shows the CMSIS pack plugin and not the CMSIS Zone plugin. Both 0.9.0 plugins were uninstalled before.
![CMSISZone_0 9 2-Install](https://user-images.githubusercontent.com/52738687/60968835-5a3ffc80-a31e-11e9-8dc0-c99f8d7b7104.png)

**Comment by jkrech** [comment]
Please un-check:      [ ] Group items by category.

**Comment by ThorstenSt** [comment]
Ah, that helps - should have tried that myself. But in v0.9.0 this was not needed as the two plug ins were grouped differently.

**Comment by edriouk** [comment]
Sorry for that, the category file still lists an older version, we'll correct it.

**Comment by edriouk** [comment]
I have uploaded the zip archive with correct category information. 
You do not need to reinstall it since it contains no other changes.
Thank you for finding the issue.
