### ISSUE TITLE
How will CMSIS-Zone integrate with build system?

### ISSUE THREAD

**Issue by KenLSoft** [ARM-software/CMSIS-Zone#4]
Hi,
Looks like this zone is for configuration files only; how is it integrated with build system? Is there any 'all-in-one' example, or we need to run the build system manually after files are generated?

**Comment by ReinhardKeil** [comment]
Ken,

The integration into a build system is not complete. Currently we copy the config files.

This is clearly something we should improve, but should not hinder you to judge on the overall concept.

Reinhard
________________________________

**Comment by KenLSoft** [comment]
Thanks for the clarify. I was thinking how to move tfm into an IDE with overall functions. Let's start with the configuration file first.
